#!/bin/bash

EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` index_dir query"
  exit $E_BADARGS
fi

LUCENE_DIR=/opt/chatyeo/utils/lucene

export CLASSPATH=$LUCENE_DIR/classes/
for file in $LUCENE_DIR/lib/*.jar; do export CLASSPATH=$file:$CLASSPATH; done

java com.chatyeo.lucene.util.RSSSearcher "$1" "$2"

