sed -i 's/http:\/\/dbpedia.org\/resource\///g' art*.nt
sed -i 's/http:\/\/www.w3.org\/2000\/01\/rdf-schema#//g' art*.nt 
sed -i 's/http:\/\/dbpedia.org\/resource\///g' art*.nt 
sed -i 's/http:\/\/www.w3.org\/1999\/02\/22-rdf-syntax-ns#//g' art*.nt
sed -i 's/http:\/\/dbpedia.org\/ontology\///g' art*.nt 
sed -i 's/http:\/\/dbpedia.org\/property\///g' art*.nt 
sed -i 's/http:\/\/xmlns.com\/foaf\/0.1\///g' art*.nt 
sed -i 's/http:\/\/www.w3.org\/2001\/XMLSchema#//g' art*.nt 
sed -i 's/http:\/\/www.w3.org\/2004\/02\/skos\/core#//g' art*.nt
sed -i 's/<Category:/</g' art*.nt
