#!/bin/bash

echo Deploying Chatyeo

cd ../chatyeo
/usr/local/erlware/bin/sinan dist
sudo /usr/local/erlware/bin/faxien ir _build/development/tar/chatyeo-0.1.0.0.tar.gz

sudo rm -fr /opt/chatyeo/wwwroot
sudo cp -R lib/chatyeo_web/wwwroot /opt/chatyeo/
sudo ln -sf /opt/erlang-libs/nitrogen/www /opt/chatyeo/wwwroot/nitrogen

sudo chmod +x /usr/local/erlware/lib/ssl-3.10.3/priv/bin/ssl_esock
